# Generated by Django 4.1 on 2022-09-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
