# Generated by Django 4.1 on 2022-09-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0003_alter_board_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
