# Generated by Django 4.1 on 2022-10-05 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pin',
            options={'ordering': ['-date_updated', '-date_created']},
        ),
    ]
