# Generated by Django 4.1 on 2022-10-06 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0007_alter_pin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='pin.pin'),
        ),
    ]
